server:
  port: 8002


spring:
  application:
    name: SERVER-CONSUMER #指定当前为服务的名字

#eureka相关配置  #要注册到的eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://wangshen:123@localhost:9999/eureka/

# 开启Hystrix熔断器
feign:
  hystrix:
    enabled: true

# 配置负载均衡，使用的调度算法
SERVER-PROVIDER:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
